### ISSUE TITLE
Clarify how CompositePrivateKey is to be placed in OneAsymmetricKey

### ISSUE THREAD

**Issue by pkelsey** [EntrustCorporation/draft-ounsworth-pq-composite-keys#13]
I think that when encapsulating a CompositePrivateKey in a OneAsymmetricKey, allowing the publicKey field of that OneAsymmetricKey to contain a CompositePublicKey would result in needless complexity, given that CompositePrivateKey already accommodates corresponding public key material.

Proposed language changes are in #11.

**Comment by ounsworth** [comment]
Hmm. You raise an interesting point: we're allowing optional private keys at both the overall composite level, and at the component level within each component OneAsymmetricKey. I'm going to leave this open for now and discuss with co-authors. The right thing might actually be the reverse: say that component OneAsymmetricKeys within a CompositePrivateKey MAY NOT contain a public key.

Reason: if an implementation wants the public key -- for example to match it against a cert to know that it has the right private key -- then we should provide it intact. Forcing the implementation to reconstruct it from the components is probably worse.

**Comment by pkelsey** [comment]
I think it's slightly more complicated than that.  In the situation where a CompositePrivateKey is stored in a OneAsymmetricKey, you might:

1. store the corresponding public keys in a CompositePublicKey in that top level OneAsymmetricKey, or
2. store either component public key in the respective component OneAsymmetricKey of the CompositePrivateKey, or
3. store either component public key in the privateKey members of the respective component OneAsymmetricKey, as typically the privateKey format for a given algorithm can also optionally contain the corresponding public key, or
4. not store either component public key at all

Here, without digressing into what to do (if anything) about the degrees of freedom in (2) and (3), I'm trying to prevent adding yet another level of potential public key storage to deal with.  The thinking is that separate from this OneAsymmetricKey container application, code will have to exist to deal with harvesting / generating corresponding component public keys given a CompositePrivateKey (that is, deal with (2)-(4)), and this code should just be reused wherever those public keys are needed.  Should a CompositePublicKey format be required specifically, it can be trivially / generically constructed given the component public keys.

**Comment by ounsworth** [comment]
Closed with #11
