### ISSUE TITLE
Composite key component ordering is sometimes ambiguous

### ISSUE THREAD

**Issue by pkelsey** [EntrustCorporation/draft-ounsworth-pq-composite-keys#14]
In the current text, we have:

- CompositePrivateKey component ordering defined as "same as CompositePublicKey"
- CompositePublicKey component ordering not clearly defined, because while component ordering is clearly defined for each explicit composite algorithm identifier, a given CompositePublicKey structure
  - may associated with a given explicit composite algorithm identifier, or
  - may be associated with the generic composite algorithm identifier, or
  - may not necessarily be associated with any specific composite algorithm identifier

The proposed language changes in #12 seek to clarify this by:

-  Setting out in the CompositePublicKey definition that component ordering is determined by the associated algorithm identifier (defaulting to id-composite-key if not otherwise specified)
- Establishing that the ordering rules are the same for CompositePrivateKey
- Making it explicit that that when id-composite-key is used, there is no ordering constraint
- Requiring future composite algorithm identifier definitions to include component ordering

**Comment by ounsworth** [comment]
Thanks @pkelsey !
I'm not git-wizardy enough to be able to merge your PR, so I took your diffs manually.

How would you like to be acknowledged in the doc? I usually do:
> First Last (company)
but I don't know your company.

**Comment by pkelsey** [comment]
> Thanks @pkelsey ! I'm not git-wizardy enough to be able to merge your PR, so I took your diffs manually.
> 
> How would you like to be acknowledged in the doc? I usually do:

Thanks for the acknowledgement.  You can use:
Patrick Kelsey (Not for Radio LLC)
