### ISSUE TITLE
Check ASN.1 in a compiler

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-pq-composite-keys#19]

**Comment by janklaussner** [comment]
Hi @ounsworth ,
I started to look at the ASN.1 code using OSS ASN.1 Syntax Checker and it fails right at the 'pk-Composite' object. This object seems to be wrong in many ways so I wonder if it works on your side and I am missing something or you wrote this free handed?

**Comment by ounsworth** [comment]
Done! Woohoo!
