### ISSUE TITLE
Should we remove OIDs?

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-pq-composite-keys#21]
Sorta no point having composite OIDs if there are no Dilithium / Falcon / Kyber OIDs.

And Russ' point is a good one: temporary OIDs end up being hard to displace.

**Comment by ounsworth** [comment]
We have every occurance of a test OID tagged with `TODO: To be replaced by IANA`, so I think it's fine.

``` 
   -- TODO: To be replaced by IANA
   id-Kyber1024-ECDH-P384-KMAC256 OBJECT IDENTIFIER ::= {
     joint-iso-itu-t(2) country(16) us(840) organization(1) entrust(114027)
     algorithm(80) explicitcomposite(5) kem(2)
     id-kyber1024-ecdh-p384(8) }
```

**Comment by johngray-dev** [comment]
We tag that the OIDs should be changed by IANA when it becomes a standard.  For early interop testing the OIDs are in use at the moment.   So we won't remove the OIDs.
