### ISSUE TITLE
Fix reference to definition of ECPrivateKey

### ISSUE THREAD

**Issue by pkelsey** [EntrustCorporation/draft-ounsworth-pq-composite-keys#22]
There are multiple references to the definition of ECPrivateKey being in RFC 5480, but ECPrivateKey is defined in RFC 5915.

**Comment by ounsworth** [comment]
Yup, that's a goof from my marathon session of digging up references.

I have 5915 in the references list, but missed linking it up.

Thanks for the detailed review to catch that!
