### ISSUE TITLE
pk-Composite in section 3.1 does not match the ASN.1 module

### ISSUE THREAD

**Issue by johngray-dev** [EntrustCorporation/draft-ounsworth-pq-composite-keys#28]
pk-Composite in section 3.1 is defined as follows:

 pk-Composite PUBLIC-KEY ::= {
       id id-composite-key
       KeyValue CompositePublicKey
       Params ARE ABSENT
       PrivateKey CompositePrivateKey
   }

It is defined in the ASN.1 module as follows: 

 pk-Composite PUBLIC-KEY ::= {
       IDENTIFIER id-composite-key
       KEY CompositePublicKey
       PARAMS TYPE CompositeAlgorithmIdentifier ARE optional
       PRIVATE-KEY CompositePrivateKey
   }

So this needs to be resolved.   

Also, Jan mentioned that for integrating the combiner modes they need parameters, so would like to keep the parameters optional.   Discussion at the next collaboration meeting needed for this item.

**Comment by ounsworth** [comment]
Re-worked section 3.1:
> The following ASN.1 Information Object Class is a template to be used
   in defining all composite key types

as well as removing this from the ASN.1 module. That closes this issue.

**Comment by johngray-dev** [comment]
This has been removed from the ASN.1 module because explicit is being used now.  In section 3.1 it is just a template model for how it will be used.
